### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by Rohit-Satyam** [raghavagps/exopropred#1]
@raghavagps @sumeetpatiyal I am getting the following error, when I try to run your tool on our data. Is there a minimum length cutoff for the input proteins. 

```
Summary of Parameters:
Input File:  subset_1455.fasta ; Threshold:  0.51 ; Model Type:  2
Output File:  outfile.csv ; Display:  2
# ############################################################################

======= Thanks for using Predict module of ExoProPred using hybrid model. Your results will be stored in file : outfile.csv  =====

###########################################################################################################################################################
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/proteinfer/bin/exopropred", line 8, in <module>
    sys.exit(main())
  File "/home/subudhak/miniconda3/envs/proteinfer/lib/python3.7/site-packages/exopropred/python_scripts/exopropred.py", line 801, in main
    lenchk(df1)
  File "/home/subudhak/miniconda3/envs/proteinfer/lib/python3.7/site-packages/exopropred/python_scripts/exopropred.py", line 80, in lenchk
    print("Error: Please provide sequence(s) with length more than 50. Input sequence at position "+i+" has length "+len(dflc['Seq'][i])+". Please check the sequences.")
TypeError: can only concatenate str (not "int") to str
```

**Comment by Rohit-Satyam** [comment]
Sorry pardon my ignorance. I see this now `Please provide sequence(s) with length more than 50.`
